APP/Models/Pages/RevuePresse/NewspaperItemViewModel.cs
using CMS.DocumentEngine.Types.AM;
using System;

namespace ArchivesDuMaroc.Models
{
    public class NewspaperItemViewModel
    {
        public string DocumentName { get; }
        public string NewspaperTitle { get; }
        public string NewspaperHeroImage { get; }
        public string NewspaperImage { get; }
        public string NewspaperYear { get; }
        public string NewspaperSource { get; }
        public string NewspaperFile { get; }
        public string NewspaperDescription { get; }
        public Guid NodeGUID { get; set; }

        public NewspaperItemViewModel(NewspaperItem NewspaperPage, string HeroImage)
        {
            DocumentName = NewspaperPage.DocumentName;
            NewspaperTitle = NewspaperPage.NewspaperTitle;
            NewspaperHeroImage = HeroImage;
            NewspaperImage = NewspaperPage.NewspaperImage;
            NewspaperYear = NewspaperPage.NewspaperYear;
            NewspaperSource = NewspaperPage.NewspaperSource;
            NewspaperFile = NewspaperPage.NewspaperFile;
            NewspaperDescription = NewspaperPage.NewspaperDescription;
            NodeGUID = NewspaperPage.Parent.NodeGUID;
        }
    }
}

APP/Models/Pages/RevuePresse/NewspapersViewModel.cs
using CMS.DocumentEngine.Types.AM;
using System;
using System.Collections.Generic;

namespace ArchivesDuMaroc.Models
{
    public class NewspapersViewModel
    {
        public string DocumentName { get; }
        public string NewspapersHeroTitle { get; }
        public string NewspapersHeroImage { get; }
        public Guid NodeGUID { get; set; }

        public List<NewspaperItem> Slider { get; }
        public List<int> Years { get; }
        public List<int> SelectedYears { get; }
        
        public NewspapersViewModel(Newspapers NewspapersPage, List<NewspaperItem> slider, List<int> years, List<int> selectedYears)
        {
            DocumentName = NewspapersPage.DocumentName;
            NewspapersHeroTitle = NewspapersPage.NewspapersHeroTitle;
            NewspapersHeroImage = NewspapersPage.NewspapersHeroImage;
            NodeGUID = NewspapersPage.NodeGUID;
            Slider = slider;
            Years = years;
            SelectedYears = selectedYears;
        }
    }
}

APP/Controllers/AccueilController.cs
using System.Web.Mvc;

using Kentico.PageBuilder.Web.Mvc;
using Kentico.Web.Mvc;

using CMS.DocumentEngine.Types.AM;
using System.Globalization;
using CMS.DocumentEngine;
using System.Linq;
using ArchivesDuMaroc.Models;
using System;

namespace ArchivesDuMaroc.Controllers
{
    public class AccueilController : BaseController
    {
        // GET: Home
        public ActionResult Index()
        {
            Home homeNode = HomeProvider.GetHome("/Home", CultureInfo.CurrentCulture.Name, _siteName)
                .Columns("DocumentName", "DocumentID", "LinkYoutube", "VideoCategory", "VideoTitle", "VideoDescription");

            if (homeNode == null)
                return HttpNotFound();
            var slider = DocumentHelper.GetDocuments<Slider>().Path("/Home/Slider", PathTypeEnum.Children).Culture(CultureInfo.CurrentCulture.Name)
                .OrderBy("NodeOrder").Columns("NodeGUID", "DocumentCulture", "NodeAlias", "Image", "Title", "Description", "DocumentPublishFrom", "DocumentPublishTo")
                .Where(m=> (m.DocumentPublishFrom == null || m.DocumentPublishFrom <= DateTime.Now) && ( m.DocumentPublishTo == null || m.DocumentPublishTo >= DateTime.Now)).ToList();

            var lastPublication = DocumentHelper.GetDocuments<PublicationItems>().Path("/Publications", PathTypeEnum.Children).Culture(CultureInfo.CurrentCulture.Name).OnSite(_siteName)
                .Columns("NodeGUID", "DocumentCulture", "NodeAlias", "PublicationTitle", "PublicationImage", "PublicationText", "NodeParentID")
                .OrderByDescending("DocumentCreatedWhen").LastOrDefault();

            var lastPublicationModel = new PublicationItemViewModel(lastPublication);

            var homeModel = new HomeViewModel(homeNode, slider, lastPublicationModel);
            HttpContext.Kentico().PageBuilder().Initialize(homeNode.DocumentID);
            return View(homeModel);
        }
    }
}

APP/Controllers/Pages/RevuePresseController.cs
using System.Web.Mvc;

using Kentico.PageBuilder.Web.Mvc;
using Kentico.Web.Mvc;

using CMS.DocumentEngine.Types.AM;
using System.Globalization;
using ArchivesDuMaroc.Models;
using CMS.DocumentEngine;
using System.Linq;
using System;
using System.Collections.Generic;
using System.Web.Http;

namespace ArchivesDuMaroc.Controllers.Pages
{
    public class RevuePresseController : BaseController
    {
        // GET: Newspapers
        public ActionResult Index([FromUri]int[] filter)
        {
            Newspapers NewspapersNode = NewspapersProvider.GetNewspapers("/Newspapers", CultureInfo.CurrentCulture.Name, _siteName)
                .Columns("DocumentName", "DocumentID", "NodeGUID", "NewspapersHeroTitle", "NewspapersHeroImage");

            if (NewspapersNode == null)
                return HttpNotFound();

            var slider = DocumentHelper.GetDocuments<NewspaperItem>().Path("/Newspapers", PathTypeEnum.Children).Culture(CultureInfo.CurrentCulture.Name)
                .OrderBy("NodeOrder").Columns("NodeGUID", "DocumentCulture", "NodeAlias", "NewspaperTitle", "NewspaperImage", "NewspaperYear", "NewspaperYear", "NewspaperDescription", "NewspaperSource", "NewspaperFile", "DocumentPublishFrom", "DocumentPublishTo")
                .Where(m => (m.DocumentPublishFrom == null || m.DocumentPublishFrom <= DateTime.Now) && (m.DocumentPublishTo == null || m.DocumentPublishTo >= DateTime.Now)).ToList();
            
            List<int> yearsList = slider.Select(s => int.Parse(s.NewspaperYear)).Distinct().ToList();
            List<int> selectedYears = new List<int>();
            if (filter != null && filter.Any())
            {
                slider = slider.Where(s => filter.Contains(int.Parse(s.NewspaperYear))).ToList();
                selectedYears = filter.ToList();
            }
            var NewspapersModel = new NewspapersViewModel(NewspapersNode, slider, yearsList, selectedYears);

            HttpContext.Kentico().PageBuilder().Initialize(NewspapersNode.DocumentID);
            return View(NewspapersModel);
        }

        public ActionResult Details(Guid id)
        {
            Newspapers NewspapersNode = NewspapersProvider.GetNewspapers("/Newspapers", CultureInfo.CurrentCulture.Name, _siteName)
                .Columns("DocumentName", "DocumentID", "NodeGUID", "NewspapersHeroImage");

            if (NewspapersNode == null)
                return HttpNotFound();

            NewspaperItem newspaperItem = NewspaperItemProvider.GetNewspaperItem(id, CultureInfo.CurrentCulture.Name, _siteName)
                .Columns("DocumentName", "DocumentID", "NodeGUID", "DocumentCulture", "NodeAlias", "NewspaperTitle", "NewspaperImage", "NewspaperYear", "NewspaperYear", "NewspaperDescription", "NewspaperSource", "NewspaperFile", "DocumentPublishFrom", "DocumentPublishTo", "NodeParentID");

            if (newspaperItem == null)
                return HttpNotFound();

            var NewspaperItemModel = new NewspaperItemViewModel(newspaperItem, NewspapersNode.NewspapersHeroImage);

            HttpContext.Kentico().PageBuilder().Initialize(newspaperItem.DocumentID);
            return View(NewspaperItemModel);
        }
    }
}

APP/Views/RevuePresse/Details.cshtml
@model ArchivesDuMaroc.Models.NewspaperItemViewModel
@using Kentico.Web.Mvc
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Archives Du Maroc - " + Model.DocumentName;
}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="block-banner banner-w-image"
                     style="background-image: url(@Url.Kentico().ImageUrl(@Model.NewspaperHeroImage, SizeConstraint.Empty))">
                    <div class="breadcrumb ">
                        <div class="container">
                            <ul>
                                <li class="home">
                                    <a style="cursor: pointer;" href="@Url.Action("", "Accueil")" title="Accueil">
                                        @Html.GetUiString("Hero.Home")
                                    </a>
                                </li>
                                @Html.Raw(Html.GetTreeLinks(Model.NodeGUID))
                                <li>@Html.ActionLink(Html.GetUiString("Home.Newspaper").ToHtmlString(), "", "RevuePresse")</li>
                            </ul>
                        </div>
                    </div>
                    <div class="container">
                        <h1 class="page_title">
                            @Model.NewspaperTitle
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="my-5 pub-detail">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-sm-12 col-md-12">
                @if (!string.IsNullOrWhiteSpace(Model.NewspaperFile))
                {
                    <embed height="1000px" width="100%" src="@Url.Kentico().FileUrl(Model.NewspaperFile, new FileUrlOptions() { AttachmentContentDisposition = true })" />
                }
            </div>
        </div>
    </div>
</section>

APP/Views/RevuePresse/Index.cshtml
@model ArchivesDuMaroc.Models.NewspapersViewModel
@using Kentico.Web.Mvc
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Archives Du Maroc - Revuue de presse";
}
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="block-banner banner-w-image "
                     style="background-image: url(@Url.Kentico().ImageUrl(@Model.NewspapersHeroImage, SizeConstraint.Empty))">
                    <div class="breadcrumb ">
                        <div class="container">
                            <ul>
                                <li class="home">
                                    <a style="cursor: pointer;" href="@Url.Action("", "Accueil")" title="Accueil">
                                        @Html.GetUiString("Hero.Home")
                                    </a>
                                </li>
                                @Html.Raw(Html.GetTreeLinks(Model.NodeGUID))
                            </ul>
                        </div>
                    </div>
                    <div class="container">
                        <h1 class="page_title">
                            @Model.NewspapersHeroTitle
                        </h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="multiple-elements press-elements">
    <div class="container">
        <form method="post">
            <div class="form-group">
                <select class="select2 form-control block select2-hidden-accessible" multiple="" readonly name="filter"
                        id="responsive_multi" style="width: 70%" data-select2-id="responsive_multi"
                        tabindex="-1" aria-hidden="true">
                    @foreach (var year in Model.Years)
                    {
                        <option value="@year" @(Model.SelectedYears.Contains(year) ? "selected='selected'" : "")>@year</option>
                    }
                </select>
                <input type="submit" class="btn btn-success btn-filter" value="@Html.GetUiString("Revue.Show")"/>
            </div>
        </form>
        <div class="row">
            <div class="col-lg-12 col-sm-12 col-md-12 font">
                <div class="row">
                    @foreach (var item in Model.Slider)
                    {
                        <div class="col-md-3 mt-4 col-sm-4">
                            <div class="item">
                                <div class="img-container">
                                    <a href="@Url.Action("Details", "RevuePresse", new { id = item.NodeGUID })">
                                        <div class="background-img"
                                             style="background-image: url(@Url.Kentico().ImageUrl(item.NewspaperImage, SizeConstraint.Empty))">
                                            <span class="card-year">@item.NewspaperYear</span>
                                        </div>
                                    </a>
                                </div>
                                <div class="item-content">
                                    <h4 class="category">
                                        <a href="@Url.Action("Details", "RevuePresse", new { id = item.NodeGUID })">
                                            <p>@item.NewspaperTitle</p>
                                        </a>
                                    </h4>
                                    <h3 class="title"><a href="@Url.Action("Details", "RevuePresse", new { id = item.NodeGUID })">@Html.Raw(item.NewspaperDescription)</a></h3>
                                    <h5>@item.NewspaperSource</h5>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts
{
<script>
    $("select").select2({
    tags: "true",
    placeholder: "@Html.GetUiString("Revue.Placeholder")",
    allowClear: true
    });
</script>
}